# Generated by Django 4.1.5 on 2023-02-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
